workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.dtje029.agaromenu
      vars:
        XCODE_WORKSPACE: "AgarIOMenu.xcodeproj"
        XCODE_SCHEME: "AgarIOMenu"
    scripts:
      - name: Build
        script: |
          xcodebuild build-for-testing \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -derivedDataPath build/DerivedData \
            -destination 'generic/platform=iOS'
      - name: Package IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/DerivedData/Build/Products/Release-iphoneos/$XCODE_SCHEME.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ipa/**/*.ipa
    publishing:
      email:
        recipients:
          - dylan10sachs@gmail.com
        notify:
          success: true
          failure: true
